Update third_party-borgmatic.md
mailcow/mailcow-dockerized-docs pull request #271
Opened 2021-05-01 15:48 UTC by sschwetz

set crypt volume to be backed up to allow for bare-metal restore

2021-05-01 20:39 UTC, andryyy commented
Hmm, not sure if we should do that. The fun part about having the maildir encrypted is easy encrypted mail backups.

We may want to comment it and add a note about it, what do you think?

Also pinging @kaechele

2021-05-01 22:48 UTC, kaechele commented
I think this actually addresses a major oversight on my end.
Borg backups are (unless otherwise instructed) encrypted locally before sent to the far end. They definitely are if set up the way I laid out in the documentation.
So also backing up the crypt volume actually would make sense for a bare metal restore.

For the sake of not producing unpleasant surprises when you actually do need to do full disaster recovery I would basically do a combination here:
- add the crypt volume by default
- add a note that for security reasons the crypt volume could also be backed up to a separate destination than the maildir and that this can be achieved by omitting the crypt volume from the docker-compose override.

2021-05-17 01:39 UTC, kaechele requested changes

2021-05-17 01:39 UTC, kaechele commented on docs/third_party-borgmatic.md
> +If for security reasons you do prefer to back up your crypt volume via another method remove  crypt-vol-1:/mnt/source/crypt:ro from the volumes in the yaml below.
Putting the crypt-vol-1:/mnt/source/crypt:ro into backticks like this: `crypt-vol-1:/mnt/source/crypt:ro` makes it a little more obvious.

2022-01-30 00:45 UTC, closed without merging