update Versions
mailcow/mailcow-dockerized-docs pull request #436
Opened 2022-06-28 10:58 UTC by Jerome2103

update Roundcube from 1.5.2 to 1.5.3
update RCMCardDAV from 4.3.0 to 4.4.1

2022-06-28 15:42 UTC, MAGICCC commented
I assume you tested it with a (fresh) install?

2022-06-28 15:47 UTC, Jerome2103 commented
Yes, it was no problem for me. Why?

2022-06-28 15:48 UTC, Jerome2103 commented
But i test this today again

2022-06-28 17:27 UTC, Jerome2103 commented
@MAGICCC 
I tested everything again and it worked.
The only thing was that it is not "mailcowdockerized_php-fpm-mailcow_1" but "mailcowdockerized-php-fpm-mailcow-1", I don't know if it's just me or it's new since v2 (dockercompose v2).

2022-06-29 19:54 UTC, MAGICCC commented
Yes it got changed with compose v2 by Docker. You can also change this :)

2022-06-29 20:07 UTC, Jerome2103 commented
i updated now include the nextcloud commands.

2022-06-30 09:16 UTC, DerLinkman requested changes
See the comment with the - the rest looks fine to me.

Thanks!

2022-06-30 09:16 UTC, DerLinkman commented on docs/third_party/third_party-nextcloud.de.md
> +Damit mailcow ein Zertifikat für die Nextcloud Domain generieren kann, muss die Domain unter welcher die Nextcloud später erreichbar sein soll als ADDITIONAL_SAN in die mailcow.conf hinzufügt werden
The one with - is the right one. There is no typo since we´ve returned to the standalone version of docker-compose with the -. (The following as well)

2022-06-30 12:35 UTC, Jerome2103 commented on docs/third_party/third_party-nextcloud.de.md
> +Damit mailcow ein Zertifikat für die Nextcloud Domain generieren kann, muss die Domain unter welcher die Nextcloud später erreichbar sein soll als ADDITIONAL_SAN in die mailcow.conf hinzufügt werden
No problem, Do I need to do anything else?

2022-06-30 19:22 UTC, MAGICCC commented
now it looks fine

2022-07-01 08:59 UTC, DerLinkman approved these changes
Now it looks good. I corrected the - in some commands.

2022-07-01 08:59 UTC, merged