Add automatic container restart to Traefik example
mailcow/mailcow-dockerized-docs pull request #487
Opened 2022-10-30 10:25 UTC by t3easy

Also switch to volume as it is more flexible than recursive path and add examples for external name

See: https://github.com/kereis/traefik-certs-dumper#automatic-container-restart

2022-10-31 11:06 UTC, DerLinkman requested changes
See comments

2022-10-31 11:06 UTC, DerLinkman commented on docs/post_installation/firststeps-rp.de.md
> +          # Bilden Sie das Volume, das Traefiks `acme.json' Datei enthält, ein
Its called "Binden" not "Bilden".

2022-10-31 11:06 UTC, DerLinkman commented on docs/post_installation/firststeps-rp.de.md
> +          # Binde den Docker socket ein um die Container neu zu starten
"Binden Sie den Docker Socket ein, damit Traefik die Container neu starten kann"

2022-10-31 11:18 UTC, t3easy commented on docs/post_installation/firststeps-rp.de.md
> +          # Binde den Docker socket ein um die Container neu zu starten
Thanks, will fix the typo later!

2022-11-03 11:02 UTC, DerLinkman approved these changes
Looks good now! Thank you

2022-11-03 11:02 UTC, merged