Update minimum docker version requirements
mailcow/mailcow-dockerized-docs pull request #733
Opened 2024-07-15 17:26 UTC by Jniklas2

Just updated the version numbers to the current major version. With the old `20.10.2`, mailcow doesn't start correctly anymore.

Maybe older versions (like version 25 or 26) are also working, I didn't test for the oldest working version.

2024-07-16 07:08 UTC, DerLinkman commented
27 is the newest Docker version?

I would not directly use this as the minimum version though.

It's even working with 24.X versions...

So i would say this is the minimum at least.

2024-07-16 07:10 UTC, DerLinkman requested changes
See comments

2024-07-16 07:10 UTC, DerLinkman commented on docs/getstarted/install.de.md
> +Sie benötigen Docker (eine Version >= `27.0.0` ist erforderlich) und Docker Compose (eine Version `>= 2.0` ist erforderlich).
27.X is the latest docker version i would not set this as a minumum as it is no minimum as it is the latest version existing.

For now lets set it to 24.X

2024-07-16 07:10 UTC, DerLinkman commented on docs/getstarted/install.en.md
> +You need Docker (a version >= `27.0.0` is required) and Docker Compose (a version `>= 2.0` is required).
Here the same of course :)

2024-07-30 15:38 UTC, MAGICCC approved these changes

2024-07-31 08:12 UTC, merged